services:
  tools:
    build:
      context: .
      target: tools
    container_name: debian_tools
    ports:
      - "2222:22"  # Mappage du port 22 du conteneur vers 2222 sur l'hôte
    stdin_open: true #active stdin (équivalent de -i)
    tty: true #active tty (équivalent de -t)
    restart: on-failure
    environment:
      TZ: Europe/Paris
    volumes:
      - ./datas:/datas
    deploy:
      resources:
        limits:
          memory: 2g  # Maximum
        reservations:
          memory: 1g  # Minimum garanti

volumes:
  datas:
  ssh-keys: