services:
  sshmarmits:
    image: ${IMAGE_NAME_DEBIAN:-debian12}
    labels:
      - "description=Système debian 12 Connexion SSH avec Key pass d'un utilisateur sudoers"
      - "role=Container directement ouvert avec divers outils et programmes utiles ou kitch installés"
      - "maintainer=marmits.com"
    build:
      context: .
      target: ${TARGET_SSH_DEV:-marmitstools}
      args:
        BASE_IMAGE: ${BASE_IMAGE:-debian:latest}
        TZ: ${TZ:-Europe/Paris}
        SSH_USER: ${SSH_USER:-debian}
    container_name: ${CONTAINER_NAME_TOOLS:-debian_tools}
    ports:
      - target: 22
        published: ${SSH_PORT:-2222} # Mappage du port 22 du conteneur vers 2222 sur l'hôte
        protocol: tcp
    stdin_open: true #active stdin (équivalent de -i)
    tty: true #active tty (équivalent de -t)
    restart: on-failure
    environment:
      BASE_IMAGE: ${BASE_IMAGE}
      TZ: ${TZ}
      SSH_USER: ${SSH_USER}
    volumes:
      - ./datas:/datas
      - ./config/.docker_bash_history:/home/${SSH_USER}/.bash_history
    secrets:    
      - source: ssh_public_key
        target: /run/secrets/ssh_public_key
    tmpfs:
      - /tmp:size=100m #éphémère en RAM
    deploy:
      resources:
        limits:
          memory: 256M   # ↓ Réduit à 256 Mo (suffisant pour un SSH)
          #cpus: "2"  # Maximum : 50% d'un cœur physique
          cpus: "0.5"    # Maintient une limite haute pour burst CPU
        reservations:
          memory: 64M    # ↓ Réduit à 64 Mo (garantie minimale)
          #cpus: "1" # Minimum garanti : 25% d'un cœur
          cpus: "0.1"    # ↓ Réduit à 10% d'un cœur
    networks:
      - my-ipv6-net

secrets:
  ssh_public_key:
    file: ${KEY_DIR}/${KEY_PREFIX}.pub

volumes:
  datas:

networks:
  my-ipv6-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80  # Sous-réseau différent