services:
  tools:
    build:
      context: .
      target: tools
    container_name: debian_tools
    ports:
      - "2222:22"  # Mappage du port 22 du conteneur vers 2222 sur l'hôte
    stdin_open: true #active stdin (équivalent de -i)
    tty: true #active tty (équivalent de -t)
    restart: on-failure
    environment:
      TZ: Europe/Paris
    volumes:
      - ./datas:/datas
      - ./startup:/startup
    tmpfs:
      - /tmp:size=100m #éphémère en RAM
    deploy:
      resources:
        limits:
          memory: 2g  # Maximum
          #cpus: "2"  # Maximum : 50% d'un cœur physique
          cpus: "0.5"  # Maximum : 50% d'un cœur physique
          pids: 100  # Nombre max de processus
        reservations:
          memory: 1g  # Minimum garanti
          #cpus: "1" # Minimum garanti : 25% d'un cœur
          cpus: "0.25" # Minimum garanti : 25% d'un cœur
    networks:
      - my-ipv6-net

volumes:
  datas:
  ssh-keys:
  startup:

networks:
  my-ipv6-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80  # Sous-réseau différent