services:
  api:
    build:
      context: .
      target: tools
    container_name: debian_tools
    stdin_open: true #active stdin (équivalent de -i)
    tty: true #active tty (équivalent de -t)
    restart: on-failure
    environment:
      TZ: Europe/Paris
    volumes:
      - ./datas:/datas
    ports:
      - "2222:22"

volumes:
  datas: