services:
  tools:
    image: ${IMAGE_NAME_DEBIAN:-debian12}
    build:
      context: .
      target: ${TARGET:-tools}
      args:
        BASE_IMAGE: ${BASE_IMAGE:-debian:latest}
        TZ: ${TZ}
    container_name: ${CONTAINER_NAME_TOOLS:-debian_tools}
    ports:
      - target: 22
        published: ${SSH_PORT:-2222} # Mappage du port 22 du conteneur vers 2222 sur l'hôte
        protocol: tcp
    stdin_open: true #active stdin (équivalent de -i)
    tty: true #active tty (équivalent de -t)
    restart: on-failure
    environment:
      TZ: ${TZ}
    volumes:
      - ./datas:/datas
      - ./startup:/startup
    tmpfs:
      - /tmp:size=100m #éphémère en RAM
    deploy:
      resources:
        limits:
          memory: 2g  # Maximum
          #cpus: "2"  # Maximum : 50% d'un cœur physique
          cpus: "0.5"  # Maximum : 50% d'un cœur physique
          pids: 100  # Nombre max de processus
        reservations:
          memory: 1g  # Minimum garanti
          #cpus: "1" # Minimum garanti : 25% d'un cœur
          cpus: "0.25" # Minimum garanti : 25% d'un cœur
    networks:
      - my-ipv6-net

volumes:
  datas:
  ssh-keys:
  startup:

networks:
  my-ipv6-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80  # Sous-réseau différent